import type { Metadata } from "next";
import "./globals.css";

import { Cormorant, Manrope, Space_Mono } from "next/font/google";

const display = Cormorant({ subsets: ["latin"], weight: ["500","600"], style: ["normal","italic"], variable: "--font-display" });
const body    = Manrope({ subsets: ["latin"], weight: ["400","500","600"], variable: "--font-body" });
const mono    = Space_Mono({ subsets: ["latin"], weight: ["400","700"], variable: "--font-mono" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${display.variable} ${body.variable} ${mono.variable}min-h-full flex flex-col`}>
        <>
        {children}
        </>
      </body>
    </html>
  );
}
